basePath: /api
definitions:
  backend.versionInfo:
    properties:
      build_date:
        type: string
      build_ref:
        type: string
      version:
        type: string
    type: object
info:
  contact:
    email: dev@appname
    name: API Support
  description: Swagger API appname
  license: {}
  termsOfService: http://swagger.io/terms/
  title: appname
  version: "0.1"
paths:
  /v1/version:
    get:
      description: Returns portal version information
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/backend.versionInfo'
      summary: Returns portal version information
      tags:
      - Misc
swagger: "2.0"
