pkcs11:
  library: /usr/lib/softhsm/libsofthsm2.so
  label: someLabel
  pin: somePin

aes:
  keylength: 32
  message: "Some Important Message"
  non-ephemeral: false
  label: aes_testkey_01

ecdsa:
  curve: P256
  message: "Some Important Message"
  non-ephemeral: false
  label: ec_testkey_01

