pkcs11:
  library: /usr/lib/softhsm/libsofthsm2.so
  label: DlbpAdapter
  pin: securekey

aes:
  keylength: 32
  message: "Some Important Message"
  non-ephemeral: false
  label: aes_testkey_01

ecdsa:
  namedCurve: P256
  message: "Some Important Message"
  non-ephemeral: false
  label: ec_testkey_01

